/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.xalnite.util;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class OptionTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Option classUnderTest = new Option();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
